### PR TITLE
Installing dotnet-ef tool

### PR DESCRIPTION
**Pull request by yanickdi**
Added dotnet-ef when installing dotnet (not sure if /sdk is the right directory to install those tools).

Doing so I am now able to run database migrations after publishing, like:

```xml
<Target Name="PrePublishTarget" AfterTargets="Publish">
    <Exec Command="echo  &quot;Migrating Database ...&quot;" />
    <Exec Command="dotnet-ef database update"/>
</Target>
```

### CODE REVIEW

**Comment by jincod** [comment]
Hi @yanickdi,

Have you check this issue https://github.com/jincod/dotnetcore-buildpack/issues/103? I've added support for dotnet local tools and it is available at `#development`. Coult you please check it for your case?

**Comment by yanickdi** [comment]
thx for your feedback, @jincod! Using dotnet local tools works, I didn't see the changes before. 

Using your commit mentioned in #103 is doing the job - as long as dotnet-tools.json is located in root.

My dotnet cli (dotnet 3.1.100@MacOS 10.15.2) is placing dotnet-tools.json in `PROJECT_ROOT/.config/dotnet-tools.json` when creating it using `dotnet new tool-manifest`, which wasn't compatible with the check in bin/compile [1]. I guess this change came with the newest release, see https://github.com/dotnet/cli/issues/10446

Anyway, `dotnet tool restore` accepts both locations (didn't try having a config in both locations at the same time). 

You can close my PR 👍
[1] https://github.com/jincod/dotnetcore-buildpack/commit/96bccdff7bbe4ca3d3e4a78b1ce14abe7fed51ed

**Comment by jincod** [comment]
Hi @yanickdi,

I've added checking for `PROJECT_ROOT/.config/dotnet-tools.json` (pushed to develop branch). If it works for you, I'll merge to master

Many thanks

**Comment by yanickdi** [comment]
thx for the quick update. tested commit https://github.com/jincod/dotnetcore-buildpack/commit/9e964664436fa4e6fd843865d4b7dc1ceee7b49b, it worked :v:

**Comment by jincod** [comment]
Implemented by https://github.com/jincod/dotnetcore-buildpack/pull/103

**Pull request closed without merging**
