### PR TITLE
Add environment variable OUTPUT_DIR

### PR DESCRIPTION
**Pull request by matyapiro31**
as I want to change dir name from `heroku_output`,
I suggest this option.

### CODE REVIEW

**Comment by jincod** [comment]
Hello @matyapiro31 

Thank you for your contribution!💪

Could you please describe your case and provide example?

**Comment by matyapiro31** [comment]
I combined Blazor and node.js application. 
Node.js's default path is `./dist`, so to combine folder, I need to change outoput path.

**Comment by jincod** [comment]
@matyapiro31 have you checked this approach?

https://github.com/jincod/AspNetCoreDemoApp/blob/3a9b29a6881695716be94ab0fc401bcfb3aab469/src/AspNetCoreDemoApp/AspNetCoreDemoApp.csproj#L11-L18

**Comment by matyapiro31** [comment]
I checked it, but I use official build packs for node.js for it, it's easy for me to add option in this build pack.

**Pull request merged**
