### PR TITLE
refactor getting net sdk and remove apt packages

### PR DESCRIPTION
**Pull request by friism**
Opening for discussion.

This is from my old buildpack: https://github.com/friism/dotnet-buildpack/blob/master/bin/compile#L60

Instead of putting the whole SDK in the slug, we just add the runtime (the SDK sits in the cache-dir).

The decreases slug size for a simple app from ~200MB to ~70MB.

### CODE REVIEW

**Comment by friism** [comment]
Doesn't look like the apt-packages are required anymore either (starting with .NET Core 2.1), so that can really simplify things

**Comment by jincod** [comment]
What do you think about this approach https://github.com/jincod/dotnetcore-buildpack/pull/16/files?
Or about using apt for install SDK https://www.microsoft.com/net/download/linux-package-manager/rhel/sdk-current?

**Comment by friism** [comment]
@jincod this is ready for review if you like the idea

**Comment by jincod** [comment]
@friism many thanks!

I'll check it

**Comment by friism** [comment]
If you want to support running migrations with `dotnet` command then this won't work (since the SDK is only in the CACHE_DIR and not slug). I think supporting migrations is a good idea...

**Pull request merged**
